// Soul food bingo content
const bingoContent = [
    { text: "Fix ya plate", icon: "🍽️" },
    { text: "Don't forget the hot sauce", icon: "🌶️" },
    { text: "Collard greens", icon: "🥬" },
    { text: "Cornbread", icon: "🍞" },
    { text: "Fried chicken", icon: "🍗" },
    { text: "Mac & cheese", icon: "🧀" },
    { text: "Sweet tea", icon: "🧋" },
    { text: "Peach cobbler", icon: "🥧" },
    { text: "Chitlins", icon: "🐷" },
    { text: "Yams", icon: "🍠" },
    { text: "Potato salad", icon: "🥔" },
    { text: "Black-eyed peas", icon: "🥣" },
    { text: "FREE", icon: "⭐", isFreeSpace: true },
    { text: "Smothered pork chops", icon: "🥩" },
    { text: "Okra", icon: "🌱" },
    { text: "Gumbo", icon: "🍲" },
    { text: "Red beans & rice", icon: "🍛" },
    { text: "Catfish", icon: "🐟" },
    { text: "Corn on the cob", icon: "🌽" },
    { text: "Biscuits", icon: "🥯" },
    { text: "Banana pudding", icon: "🍌" },
    { text: "Barbecue ribs", icon: "🍖" },
    { text: "Sweet potato pie", icon: "🥧" },
    { text: "Turnip greens", icon: "🥬" },
    { text: "Hush puppies", icon: "🍤" },
    { text: "Turkey necks", icon: "🦃" },
    { text: "Pickled pig's feet", icon: "🐖" },
    { text: "Cracklins", icon: "🥓" },
    { text: "Rice & gravy", icon: "🍚" },
    { text: "Chicken & waffles", icon: "🧇" },
    { text: "Grits", icon: "🍚" },
    { text: "Ham hocks", icon: "🍖" },
    { text: "Mustard greens", icon: "🥬" },
    { text: "Fried okra", icon: "🌱" },
    { text: "Pinto beans", icon: "🥣" },
    { text: "Molasses", icon: "🍯" },
    { text: "Souse meat", icon: "🥩" },
    { text: "Stewed tomatoes", icon: "🍅" },
    { text: "Neck bones", icon: "🍖" },
    { text: "Pig tails", icon: "🐖" },
    { text: "Cabbage", icon: "🥬" },
    { text: "Fried green tomatoes", icon: "🍅" },
    { text: "Liver & onions", icon: "🧅" },
    { text: "Oxtails", icon: "🐂" },
    { text: "Cracklin' bread", icon: "🍞" },
    { text: "Butter beans", icon: "🫘" },
    { text: "Sorghum syrup", icon: "🍯" },
    { text: "Chow chow", icon: "🥒" },
    { text: "Bread pudding", icon: "🍞" }
]; 